# Generated by Django 4.2.4 on 2023-08-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("producer_consumer_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="task_id",
            field=models.CharField(max_length=63),
        ),
    ]
